# Generated by Django 3.2.15 on 2025-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0002_onetimepassword_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
