# Generated by Django 3.2.15 on 2025-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0003_onetimepassword_last_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_percentage',
            field=models.FloatField(default=35.0),
        ),
    ]
