# Generated by Django 3.2.15 on 2025-04-21 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0005_auto_20250418_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='status',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passing_percentage',
            field=models.FloatField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='result',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempted_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='ended_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='final_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='wrong_answers',
            field=models.IntegerField(),
        ),
    ]
